services:
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
  mongo:
    image: mongo
    ports:
      - 27017:27017
  app:
    build: .
    environment:
      RABBITMQ_URI: amqp://rabbitmq:5672
      MONGODB_URI: mongodb://mongo:27017/app
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
      - mongo
